# Generated by Django 4.0.4 on 2022-05-26 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('real', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detail',
            old_name='bathRoom',
            new_name='bathroom',
        ),
        migrations.RenameField(
            model_name='detail',
            old_name='bedRooms',
            new_name='bedrooms',
        ),
    ]
