# Generated by Django 4.0.4 on 2022-05-26 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('real', '0002_rename_bathroom_detail_bathroom_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detail',
            old_name='bathroom',
            new_name='bathroom_no',
        ),
        migrations.RenameField(
            model_name='detail',
            old_name='bedrooms',
            new_name='bedrom_no',
        ),
    ]
