# Generated by Django 4.0.4 on 2022-05-27 11:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('real', '0005_alter_detail_bathroom_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='description',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
